name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: 23f3002530@ds.study.iitm.ac.in
        run: echo "This is a step containing my email address."
